### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by skampus** [CaptainDang/save_all#1]
ciao, 
I report that with the QGIS 3.32 Lima version there is an installation error

Impossibile caricare il plugin 'SaveAllScript' a causa di un errore chiamando il metodo classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaveAllScript\__init__.py", line 36, in classFactory
    return SaveAll(iface)
  File "C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SaveAllScript\save_all.py", line 59, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.32.0-Lima Lima, 311a8cb8a65 

Percorso Python:
C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\csv_tools
C:/OSGeo4W/apps/qgis/./python
C:/Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\Users\Campus\Documents
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cgl_tools
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cgl_tools\extlibs
C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlrd-1.2.0-py2.py3-none-any.whl
C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\excel_sync\libs\xlwt-1.3.0-py2.py3-none-any.whl
C:\Users/Campus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\limburg_flood_impact_plugin\deps\limburg_flood_impact-0.4.1-py3-none-any.whl
C:\Users\Campus\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

**Comment by CaptainDang** [comment]
Hi, it seems like you are having a similar issue that people have had with other plugins. I would direct you to https://github.com/PANOimagen/batch_hillshader/issues/4

It seems that deleting the plugin folder and reinstalling helped others. I installed the latest version of QGIS (3.32 RC) and was able to install the plugin with no problems. Please let me know if you still have trouble, and I am happy to keep looking into it.

**Comment by AlisterH** [comment]
I believe you need to change this:
```
        locale = QSettings().value('locale/userLocale')[0:2]
```
to this:
```
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
```
